name: CI Workflow

on:
  push: ###########################################     Regresar a cambiarlo
    branches:
      - examen-workflows   # ✅ REGRESAR A CAMBIARLO

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'   # ✅ Setup Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt   # ✅ Instalación dependencias

      - name: Run tests with pytest
        env:
          API_KEY: ${{ secrets.API_KEY }}   # ✅ Variable de entorno desde Secrets
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          pytest --maxfail=1 --disable-warnings -q   # ✅ Ejecución tests